module.exports = {
  googleClientID: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  linkedInClientID: process.env.LINKEDIN_CLIENT_ID,
  linkedInClientSecret: process.env.LINKEDIN_CLIENT_SECRET,
  mongoURI: process.env.MONGO_URI,
  cookieKey: process.env.COOKIE_KEY,
  stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY,
  twilioSID: process.env.TWILIO_SID,
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN,
  nexmoKey: process.env.NEXMO_KEY,
  nexmoSecret: process.env.NEXMO_SECRET,
  nexmoNumber: process.env.NEXMO_NUMBER,
  s3Bucket: process.env.S3_BUCKET,
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID,
  awsSecretAccess: process.env.AWS_SECRET_ACCESS,
  jwtSecretKey: process.env.JWT_SECRET,
  googleRecaptchaSiteKey: process.env.GOOGLE_RECAPTCHA_SITE_KEY,
  googleRecaptchaSecretKey: process.env.GOOGLE_RECAPTCHA_SECRET_KEY,
  tangoPlatformName: process.env.TANGO_PLATFORM_NAME,
  tangoKey: process.env.TANGO_KEY,
  tangoAccountName: process.env.TANGO_ACCOUNT_ID,
  tangoCustomerName: process.env.TANGO_CUSTOMER_ID,
  sendGridKey: process.env.SENDGRID_KEY
};
